# Converting Text to features

In [ ]:
import warnings
warnings.filterwarnings('ignore')
from encoder import Model
model = Model()

import pandas as pd
import numpy as np
df = pd.read_csv('final_data1.csv')
questions = np.array(df['0'])
features = model.transform(questions)
np.save('final_data1_features',features)
features = np.load('final_data1_features')

# Findind similar questions

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

#np.array([1,3,2,4,5]).argsort()[-5:][::-2]
def get_qus(text):
    test_fea = model.transform(text)
    sim_list = np.empty([len(features)])
    for i in range(len(features)):
        sim_list[i] = cosine_similarity(test_fea,features[i])
    x = sim_list.argsort()
    return x[-5:]

query = ["is abortion safe?"]
similar_ques  = get_qus(query)
questions[similar_ques]

In [ ]:
df2 = pd.read_csv('data.csv')
questions2 = np.array(df2['0'])
q_vec = model.transform(questions2)
np.save("data_fea",q_vec)

def similar(text):
    vec = model.transform(text)
    for i in range(len(questions)):
        print(cosine_similarity(vec,q_vec[i]))
def get_qus_all(text):
    test_fea = model.transform(text)
    sim_list = np.empty([344])
    for i in range(155):
        sim_list[i] = cosine_similarity(test_fea,q_vec[i])
    for i in range(189):
        sim_list[155+i] = cosine_similarity(test_fea,features[i])
    x = sim_list.argsort()
    return x[-5:]

In [ ]:
qs = get_qus_all(["tell me about french kissing?"])
print(qs)
for i in qs:
    if i<155:
        print(questions[i])
    else:
        print(questions2[i-155])

# Tensorflow data feeding

In [1]:
import tensorflow as tf
import numpy as np
my_data = np.load('data_fea.npy')

In [2]:
len(my_data)

155

In [37]:
x= tf.placeholder(tf.float32,[None,4096])
w = tf.Variable(tf.ones([4096,2]))
y = tf.nn.softmax(tf.matmul(x,w))

init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    y = sess.run(y,feed_dict = {x:my_data[10:20]})
    print(y)

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]
 [ 0.5  0.5]]


In [32]:
sess = tf.Session()
x= tf.placeholder(tf.float32,[None,4096])
w = tf.Variable(tf.ones([4096,2]))
y = tf.matmul(x,w)
data_x = my_data[0]
sess.run(tf.initialize_all_variables())
sess.run(y,feed_dict={x:my_data})

Instructions for updating:
Use `tf.global_variables_initializer` instead.


array([[-38.20014572, -38.20014572],
       [-54.34017563, -54.34017563],
       [-12.71703529, -12.71703529],
       [-43.32466507, -43.32466507],
       [-28.31352234, -28.31352234],
       [-13.25005913, -13.25005913],
       [-46.45652771, -46.45652771],
       [-52.85400391, -52.85400391],
       [-72.90216827, -72.90216827],
       [-45.32616425, -45.32616425],
       [-44.99248123, -44.99248123],
       [-31.51925468, -31.51925468],
       [-14.92859745, -14.92859745],
       [-52.67435837, -52.67435837],
       [-60.89894485, -60.89894485],
       [-62.24778748, -62.24778748],
       [-58.33148956, -58.33148956],
       [-65.78419495, -65.78419495],
       [-45.58614349, -45.58614349],
       [-20.04774475, -20.04774475],
       [-41.36686707, -41.36686707],
       [-47.12547302, -47.12547302],
       [-43.39011765, -43.39011765],
       [-39.93024063, -39.93024063],
       [-49.51557159, -49.51557159],
       [-47.54880524, -47.54880524],
       [-23.11667633, -23.11667633],
 

In [28]:
def data_iter():
    while True:
        for id in range(0,len(features))

array([-0.01808685,  0.43451461, -0.01227654, ...,  0.92707855,
       -0.02581446, -0.16153637], dtype=float32)

In [35]:
team_id = 501351388
password = 'jit949'

In [8]:
a = np.array([[1,2,3],[4,5,6]])

In [10]:
a[:,:-1]

array([[1, 2],
       [4, 5]])

In [43]:
import pandas as pd
df = pd.read_csv('questions.csv')

In [56]:
df.iloc[20000]['question1']

'Which players have scored the most goals direct from free-kicks in the premiership? (and other top leagues)'

In [4]:
import os
import numpy as np

In [3]:
for file in os.listdir("/home/squiba/Documents/"):
    print(file)

1.xcf
ANN.docx
com.jpg
1.jpeg
hypr.pdf
ANN.pdf
2.jpeg
04554208.pdf
04220812.pdf
ThinkandGrowRichebook.pdf
BTPMTE2017.pdf
Optimal Control .pdf
Numerical Methods.pdf


In [6]:
x = np.ones([10000,3])
len(x)
import math
print(math.ceil(3.4))

4


In [ ]:
def data_iter():
    for datafile in os.listdir("quora_data"):
        data = np.load(datafile)
        chunk = len(data)/batch_size
        for i in range(chunk):
            feature,label = data[batch_size*i:batchsize*(i+1)][:,:-1], data[chunk*i:chunk*(i+1)][:,-1:]
            yield feature,label